### ISSUE TITLE
is cPickleCache tested?  

### ISSUE THREAD

**Issue by jimfulton** [zopefoundation/persistent#102]
Looking at the tests in test_picklecache, it looks like they're only testing the Python version.

Am I missing something?

**Comment by jamadden** [comment]
The C implementation is tested indirectly via `persistent.tests.test_persistence.CPersistentTests`, but yeah, `test_picklecache` is missing the necessary subclass to run the explicit tests.

**Comment by jimfulton** [comment]
Thanks!
