### ISSUE TITLE
Building Linux wheels seems to be broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/persistent#113]
See https://travis-ci.org/zopefoundation/persistent/builds/530228105

**Comment by jamadden** [comment]
Yeah, I've seen that before. IIRC the version of `auditwheel` is tightly tied to `wheel` and you can't upgrade `wheel` in the docker image without having this issue.

We should perhaps move on to the manylinux2010 image anyway (which still has this issue, but at least has a newer compiler). It will still generate manylinux1 tagged wheels if possible.

**Comment by mgedmin** [comment]
This looks like https://github.com/pypa/auditwheel/issues/102, filed in 2018, so how come we haven't seen this problem before now?

**Comment by jamadden** [comment]
The [release of persistent 4.4.2](https://pypi.org/project/persistent/4.4.2/#files) from August 2018 has manylinux wheels; the [release of persistent 4.4.3](https://pypi.org/project/persistent/4.4.3/#files) from the end of October 2018 (*after* the release of wheel which broke auditwheel) does **not**. So we have had the problem before, we just didn't notice.
