### ISSUE TITLE
intern keys of object state

### ISSUE THREAD

**Issue by davisagli** [zopefoundation/persistent#15]
We might want to intern() the keys of the persistent object state as they are updated in the instance dict. i.e.

```
    def __setstate__(self, state):
        for k, v in state.items():
            self.__dict__[intern(k)] = v
```

cPickle normally does this via the BUILD opcode (https://github.com/python/cpython/blob/master/Modules/_pickle.c#L5958), but ZODB pickles the object type and state separately, so that opcode is not used.

Experimentation on one client project shows about 25% memory savings when loading all instances of a particular commonly used class, with negligible effect on performance. But more careful evaluation is warranted.

(Memory use could also be reduced by using a class with slots, but that requires more invasive changes to the application code.)

**Comment by tseaver** [comment]
SLAGITM

**Comment by mgedmin** [comment]
Seems like a good idea to me too.

**Comment by tseaver** [comment]
Via #16.
