### ISSUE TITLE
Move to the src/ layout?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/persistent#158]
This is one of the few zopefoundation repos (mostly older ones) that use a bare directory in the root of the project instead of nesting it beneath src/. That makes it annoyingly semi-unique, and has some issues of its own.

Can we move persistent to src/persistent?

**Comment by freddrake** [comment]
I'm in favor of using the src/ layout generally.

*Switching* to the src/ layout is more difficult, mostly because it's harder to follow the commit history across moves & renames.

**Comment by icemac** [comment]
I think there was a consensus to use the src/ layout in all zopefoundation packages as it has benefits in its own and using it all over the place adds another benefit.
