### ISSUE TITLE
Building a wheel fails on GHA for PyPy2 on Windows

### ISSUE THREAD

**Issue by icemac** [zopefoundation/persistent#167]
In https://github.com/zopefoundation/ZODB/pull/357 I am trying to run the ZODB tests on GHA. This requires to build a wheel for `persistent` which fails there:

See https://github.com/zopefoundation/ZODB/runs/4114338645?check_suite_focus=true

Currently we do not seem to build this combination (PyPy2 on Windows) here as AppVeyor only runs Python builds.

I do not have access to a Windows machine and maybe I did not understand the error log correctly.

Any ideas how to solve this issue?

**Comment by dataflake** [comment]
This is outdated, at this point the package does not support Python 2 / Pypy 2 anymore.
