### ISSUE TITLE
The python 3.11 wheel for linux x86 is missing

### ISSUE THREAD

**Issue by wosc** [zopefoundation/persistent#179]
I'm not fully up to date with wheel classifiers, but I think I'm reading https://pypi.org/project/persistent/4.9.3/#files correctly that there is only a linux/arm wheel on pypi currently, but no x86_64 one. (There is one for 3.10, though.)

This causes e.g. this kind of error, because pip tries to build from sdist instead:

```
$ docker run --rm -it python:3.11.0-slim pip install persistent==4.9.3
  Building wheel for persistent (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
      gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.11 -c src/persistent/cPersistence.c -o build/temp.linux-x86_64-cpython-311/src/persistent/cPersistence.o
      error: command 'gcc' failed: No such file or directory
```

**Comment by icemac** [comment]
We are using the containers quay.io/pypa/manylinux2010_x86_64 resp. quay.io/pypa/manylinux2010_i686 to build the linux wheels. The lastest versions of that containers seem to contain Python 3.6 up to 3.10 as well as PyPy 3.7 and 3.8 but no Python 3.11.
Please create an issue at pypa, when this is fixed on their side we can rerun the release process to produce the missing wheels.

**Comment by wosc** [comment]
If I'm reading this correctly, I'm afraid that [manylinux2010 is no longer supported as of 2022-08-01](https://github.com/pypa/manylinux/issues/1281), and 3.11 will not be made available there. I think you'll need to update the build process to at least `manylinux2014`, or even the most current version `manylinux_2_28` (2_24 seems to [have issues](https://github.com/h5py/hdf5-manylinux/issues/6#issuecomment-1297577145), [via](https://github.com/pypa/manylinux/issues/1317)) to get 3.11.

**Comment by icemac** [comment]
This suggestion is implemented in https://github.com/zopefoundation/meta/pull/183.

**Comment by wosc** [comment]
That sounds great, thank you! I'm looking forward to the next releases then. :)

**Comment by icemac** [comment]
Please try if the result works for you.

**Comment by wosc** [comment]
The 5.0 wheel works perfectly with python-3.11, thank you!
