### ISSUE TITLE
Who uses `persistent.cPersistence.simple_new`?

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/persistent#206]
I can't find any use of it in `BTrees` or `ZODB`.  AFAICT, it is a fossil, and it has some bad behaviour (see https://github.com/zopefoundation/persistent/pull/204/commits/da8067d2b4dfac5877d1cf2450f33f09097a2a70 which drops testing it with `type` and `tuple` because deallocating the returned instances trigger assertions).

I'm guessing it is left over from some ancient days:  I cannot find another ZODB-related project which uses it, nor any in the Zope3 and Zope2 repos I have hand.

**Comment by gforcada** [comment]
Maybe adding a deprecation warning can help to raise awareness? Or at least we can we warned before deleting it.

**Comment by davisagli** [comment]
@gforcada Tbh, I would just remove it. In the unlikely case that something depends on it, it's easy enough to revert it.

**Comment by tseaver** [comment]
@davisagli 
> Tbh, I would just remove it. In the unlikely case that something depends on it, it's easy enough to revert it.

One clue that it is unused is that it is *not* mirrored into the `PURE_PYTHON` side.
