### ISSUE TITLE
Test failure in test_hash_equal on py2.6 windows 

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/persistent#21]
Commit 2a8313ccad80cbc01f5153a55788ab8b5412bc04 breaks tests on winbot

see here:

http://winbot.zope.org/builders/persistent_py_265_32/builds/971/steps/test/logs/stdio

**Comment by agroszer** [comment]
@jamadden ^

**Comment by mgedmin** [comment]
I have a feeling this is because the tests run on a 32-bit build rather than because it's Windows or because it's Python 2.6.

Note that `hash('a string')` will differ on 32- and 64-bit platforms (and also different Python versions may compute different hashes):

```python
>>> hash('a string')  # Python 2.6.5, Linux, 32-bit
1827144452
>>> hash('a string')  # Python 2.6.9, Linux, 64-bit
-8411828025894108412
>>> hash('a string')  # Python 3.4.2, Linux, 64-bit
-8227545103199816438
```

**Comment by mgedmin** [comment]
At some point Travis CI might allow us to test both 32- and 64-bit builds in the build matrix: https://github.com/travis-ci/travis-ci/issues/986

**Comment by mgedmin** [comment]
Okay, string hashes are irrelevant for this issue: https://github.com/zopefoundation/persistent/blob/663497de550ef21c561480bfc49b7d4449dcdd04/persistent/_timestamp.c#L155-L167

**Comment by mgedmin** [comment]
Perhaps it would be sufficient to replace `ctypes.c_int64` with `ctypes.c_long` in pyTimeStamp.\__hash__?

**Comment by jamadden** [comment]
It will depend on the platform. The C implementation uses `long`, which can be either 4 or 8 bytes. It's [always 4 bytes](https://msdn.microsoft.com/en-us/library/cc953fe1.aspx) under Microsoft compilers, [I think](http://ivbel.blogspot.com/2012/02/size-of-primitive-types-in-c-language.html), but under gcc/clang it depends on whether the code is being compiled as 64-bit or not. 

Rather than trying to detect those differences in python, what about making the C implementation use `long long`, which in practice is always 8 bytes? That way the hash is consistent regardless of platform, and the Python code doesn't have to try to figure it out.

**Comment by jamadden** [comment]
Oh, nuts, that won't work, the signature of the C type object `hashfunc` is incompatible. Never mind.

**Comment by mgedmin** [comment]
Unfortunately the test still fails: http://winbot.zope.org/builders/persistent_py_265_32/builds/972/steps/test/logs/stdio

```
Failure in test test_hash_equal_constants (persistent.tests.test_timestamp.PyAndCComparisonTests)
Traceback (most recent call last):
  File "c:\Python26_32\lib\unittest.py", line 279, in run
    testMethod()
  File "c:\buildslave\persistent\build\persistent\tests\test_timestamp.py", line 302, in test_hash_equal_constants
    self.assertEqual(hash(c), 1000006000001)
  File "c:\Python26_32\lib\unittest.py", line 350, in failUnlessEqual
    (msg or '%r != %r' % (first, second))
AssertionError: -721379967 != 1000006000001L
```

```
Failure in test test_py_hash_32_64_bit (persistent.tests.test_timestamp.PyAndCComparisonTests)
Traceback (most recent call last):
  File "c:\Python26_32\lib\unittest.py", line 279, in run
    testMethod()
  File "c:\buildslave\persistent\build\persistent\tests\test_timestamp.py", line 275, in test_py_hash_32_64_bit
    self.assertEqual(hash(py), bit_64_hash)
  File "c:\Python26_32\lib\unittest.py", line 350, in failUnlessEqual
    (msg or '%r != %r' % (first, second))
AssertionError: 1979033151 != -3850693964765720575L
```

**Comment by mgedmin** [comment]
The 1st failure (test_hash_equal_constants) is the same as before.  The failure in test_hash_equal is gone.  The failure in test_py_hash_32_64_bit is new.

**Comment by jamadden** [comment]
In `test_py_hash_32_64_bit`, I probably need to directly call `__hash__` to avoid the interpreter's built-in truncating of the 64-bit value.

As for the constants, sorry I missed those the first time around. I obviously calculated those based on a 64-bit platform. What if we skip that test on a 32-bit platform?

**Comment by jamadden** [comment]
By the way, these failures don't go to the "zope-dev" mailing list, like, for example, the zope.toolkit failures do. Is there some other list they go to so I could catch them earlier?

**Comment by jamadden** [comment]
I found a 32-bit Python to test on, so hopefully PR #23 should really do it.

**Comment by mgedmin** [comment]
The failures go to zope-tests@zope.org, and then a [daily summary](http://docs.zope.org/zopetoolkit/process/buildbots.html#informing-the-zope-developer-community-about-build-results) is sent to zope-dev@zope.org (but it's basically delayed by a whole day).  I use [this script](https://gist.github.com/mgedmin/4995950) to analyze the daily summaries in a non-painful way.

**Comment by jamadden** [comment]
Thank you.
