### ISSUE TITLE
RFE: please move `src/persistent/tests/` to `tests/`

### ISSUE THREAD

**Issue by kloczek** [zopefoundation/persistent#211]
Looks like currently test suite is installed and are part of generated .whl archive.
Easiest way to exclude test suite is move `src/persistent/tests/` to `tests/`.

**Comment by dataflake** [comment]
This is not planned because that would make `persistent` a one-off among more than 300 `zopefoundation` packages that are all structured the same way.

**Comment by kloczek** [comment]
NONE of those included test suites i used by any other modules 🤔 
Looks like someone started something which installs never used code and other just blindly are following ..

**Comment by d-maurer** [comment]
Tomasz Kłoczko wrote at 2024-9-24 18:31 -0700:
>NONE of those included test suites i[s] used by any other modules ?

One of the major `zopefoundation` packages is `ZODB`.
Its tests are widely used (via inheritance) by packages depending on `ZODB`,
e.g. `ZEO` (one of the ZODB storages).

The ZODB tests are specially designed for this use and
have the general structure:

     class XXXTests(TestCase):
         def create_storage(self): ...

	 ... XXX tests ...

A storage can then use:
     class XXXTests(ZODB...XXXTests):
         def create_storage(self): ...

to execute the XXXTests with this storage.

Thus, at least for `ZODB`, having the tests easily importable
is important.


>Looks like someone started something which installs never used code and other just blindly are following ..

I have not participated in the decision where to place the tests
for `zopefoundation` packages.
But in my own packages, I always install tests and documentation beside
the executable code -- to make them easily accessible for users:
they form valuable resources for the user and having them beside
the code avoid the need to search for them.
Documentation and tests only form a small part of the required storage
resources. Thus, it should not be a severe problem to have them
installed even needed only in some cases.

For my (and many `zopefoundation`) packages, the tests can serve
as additional documentation (especially `doctest`s). Users may happy
to easily access them.

**Comment by dataflake** [comment]
> NONE of those included test suites i used by any other modules 🤔 Looks like someone started something which installs never used code and other just blindly are following ..

You misunderstood my point. I am not saying they are where they are because other packages re-use them. I am saying all 300+ zopefoundation packages have their tests within the source code tree and that's where all our own project management toolchain expect them. Making the change here makes maintenance harder.

**Comment by kloczek** [comment]
Do you know that `persistent` test suite is used by ANY other module? 🤔

**Comment by dataflake** [comment]
No it is not. I repeat, that is not the point. Please stop posting about it.
