### ISSUE TITLE
Must `_p_invalidate` call `_p_deactivate`?

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/persistent#25]
There are tests in ZODB which failed when the pure-Python `Persistent._p_invalidate` skipped explicitly calling `_p_deactivate`.

See: https://github.com/zopefoundation/persistent/pull/20#discussion-diff-30590948

**Comment by jamadden** [comment]
Other than the failing tests, I have no opinion on this. Our own code doesn't override `_p_invalidate` or `_p_deactivate`, and neither do any of the libraries we use. But it's not impossible that someone somewhere is relying on this.

**Comment by tseaver** [comment]
Consensus [seems to be](https://github.com/zopefoundation/persistent/pull/20#discussion_r30610114) "Yes, `_p_invalidate` must call `_p_deactivate`."
