### ISSUE TITLE
Must `_p_mtime` activate a ghost?

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/persistent#26]
The C implementation does forcibly activate it, while the pure-Python version (until #20) did not.

See: https://github.com/zopefoundation/persistent/pull/20/#discussion-diff-30595084

**Comment by jamadden** [comment]
Is there any other reliable way to know that an object has definitively been saved at least once, besides the fact that it has a `_p_mtime`? That's what our code uses it for. 

It's a convenience, in that case, that `_p_mtime` activates the object. If it did not, code like this:
```python
if obj._p_mtime:
   # we've been saved before
else:
   # we're a brand new object, do first-time stuff
```
has to become:
```python
obj._p_activate()
if obj._p_mtime:
   # ...
...
```

Could that code be changed everywhere? Sure. Would it be moderately annoying and an easily-missed source of bugs? Sure.

**Comment by tseaver** [comment]
I believe the consensus answer is "Yes, `_p_mtime` must activate the object."  I don't know that we every got the rationale documented, but #20 makes it so for pure-Python.
