### ISSUE TITLE
Upstream tarball contains __pycache__/*.o files

### ISSUE THREAD

**Issue by warsaw** [zopefoundation/persistent#27]
The persistent-4.1.0.tar.gz file on PyPI appears to contain `__pycache__/*.o` files from cffi.  This is problematic for downstream consumers because the binary files don't correspond directly to source files.  For example, this violates Debian policy, so the upstream tarball must be repacked to be made compliant with policy.  

I'm guessing this is just an artifact of the release process rather than something you actually want to do.

**Comment by mgedmin** [comment]
Would a 4.1.1 release without those be helpful?

(Ha ha I can't do releases of 'persistent' anyway, only @jimfulton and @tseaver can.)

**Comment by mgedmin** [comment]
(Shameless plug: using [check-manifest](https://pypi.python.org/pypi/check-manifest) prevents this kind of mistake.  It also integrates with [zest.releaser](https://pypi.python.org/pypi/zest.releaser) seamlessly, if pip installed.)

**Comment by warsaw** [comment]
On Jun 02, 2015, at 12:12 AM, Marius Gedminas wrote:

>Would a 4.1.1 release without those be helpful?

Yes, please!

**Comment by tseaver** [comment]
https://pypi.python.org/pypi/persistent/4.1.1
