### ISSUE TITLE
Tests fails on Windows, Python3, 64bit machine, likely due to float == double on windows

### ISSUE THREAD

**Issue by fgregg** [zopefoundation/persistent#38]
The failures are

```
======================================================================
FAIL: test_hash_equal (persistent.tests.test_timestamp.PyAndCComparisonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\persistent\persistent\tests\test_timestamp.py", line 260, in test_hash_equal
    self.assertEqual(hash(c), hash(py))
AssertionError: 2875592705 != -1419374591

======================================================================
FAIL: test_hash_equal_constants (persistent.tests.test_timestamp.PyAndCComparisonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\persistent\persistent\tests\test_timestamp.py", line 327, in test_hash_equal_constants
    self.assertEqual(hash(c), -721379967)
AssertionError: 3573587329 != -721379967
```

The hashes are equal mod 2**32. The tests pass on winbot, which is running a 32-bit Python.

The failing AppVeyor build is using a 64-bit Python.

This looks like a genuine bug in the test suite:

```
    def test_hash_equal_constants(self):
        ...
        is_32_bit = persistent.timestamp.c_long == ctypes.c_int32 or _is_jython                                                                     
        ....
        if is_32_bit:
            self.assertEqual(hash(c), -721379967)
        else:
            self.assertEqual(hash(c), 1000006000001)
```

On 64-bit Windows long is 32-bits long.

**Comment by tseaver** [comment]
@jamadden I'm befuzzled:  do you have a clue how to deal with tine Windows ABI-compatible-with-Win95 insanity here?

**Comment by jamadden** [comment]
@tseaver Sorry, I know I wrote this test initially. I don't know what the right fix is, though. And my Windows VM bit the dust, so I don't currently have access to experiment/test there. My only suggestion would be to skip this one on 64-bit Win?

**Comment by jamadden** [comment]
Although, skipping may not be that great an option. It's not just the test that's failing, apparently. The first test failure is actually showing a bug, the C and Python versions are different:
```
   self.assertEqual(hash(c), hash(py))
AssertionError: 2875592705 != -1419374591
```

**Comment by jamadden** [comment]
`ctypes.sizeof(c_long()) == 4` may be a better way to spell `is_32_bit`.

Except, it looks like is the problem that `ctypes.c_long` doesn't match what the actual extension module thinks of as `long`. (Because if it did match, I don't understand why `hash( c) != hash(py)`)

**Comment by jamadden** [comment]
I think I may have found it, and it's a bug in the C code. The C hash function is defined as `static long TimeStamp_hash(self)`. But the `hashfunc` slot is defined to return a `Py_ssize_t`. 

On 64-bit windows, `Py_ssize_t` is 8 bytes long, where `long` is 4 bytes. 

I instrumented both the Python and C implementations, and verified that they both *return* the same on 64-bit windows; but by the time the internal magic of C and/or the interpreter have their way with the return type, -1419374591 becomes 2875592705.

If I fix the return type, all the tests pass on Windows.

I have to verify the signature of `hashfunc` on 2.7 (been testing on 3.5) and check a sane platform, but if that holds up, PR coming.

**Comment by jamadden** [comment]
#39 does it. All builds green.
