### ISSUE TITLE
zope.wheelbuilder needs to be registered as a maintainer of pypi

### ISSUE THREAD

**Issue by fgregg** [zopefoundation/persistent#40]
Travis and Appveyor can't upload the wheels to pypi because zope.wheelbuilder is not registered maintainer of the persistent package on pypi.

**Comment by tseaver** [comment]
I've added the role.  I don't know whether we can re-trigger the Appveyor build for the tag, but I've restarted the `TERRYFY_PYTHON` jobs on Travis.

**Comment by fgregg** [comment]
Non need to restart the appveyor builds, the one for the tag hasn't started yet https://pypi.python.org/pypi/persistent
