### ISSUE TITLE
please adhere to distutils valid version numbers

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/persistent#65]
py 2.7 distutils says:

```
class StrictVersion (Version):

    """Version numbering for anal retentives and software idealists.
    Implements the standard interface for version number classes as
    described above.  A version number consists of two or three
    dot-separated numeric components, with an optional "pre-release" tag
    on the end.  The pre-release tag consists of the letter 'a' or 'b'
    followed by a number.  If the numeric components of two version
    numbers are equal, then one with a pre-release tag will always
    be deemed earlier (lesser) than one without.

    The following are valid version numbers (shown in the order that
    would be obtained by sorting according to the supplied cmp function):

        0.4       0.4.0  (these two are equivalent)
        0.4.1
        0.5a1
        0.5b3
        0.5
        0.9.6
        1.0
        1.0.4a3
        1.0.4b1
        1.0.4

    The following are examples of invalid version numbers:

        1
        2.7.2.2
        1.3.a4
        1.3pl1
        1.3c4

    The rationale for this version numbering system will be explained
    in the distutils documentation.
    """
```

winbot uses that, fails on recent 4.2.4.2 versions

**Comment by tseaver** [comment]
4.2.4.1 and 4.2.4.2 were "packaging-only" fixes.  FWIW, given that they were only about getting `manylinux` wheels built, the practical effect for Windows users is nil:  they can use 4.2.4, which is fully equivalent.

**Comment by mgedmin** [comment]
I'm not sure pip/buildout is clever enough to look for older versions if the latest version on PyPI lacks wheels/eggs for the user's platform.

BTW @agroszer the [packaging](https://pypi.python.org/pypi/packaging) package on PyPI has a Version class that can handle all PEP-440-compliant versions, which include "4.2.4.2".

**Comment by tseaver** [comment]
I guess the real near-term solution would be to close another bug or two and release a 4.2.5 version.

**Comment by jamadden** [comment]
4.3.0 has been released to PyPI. Travis and Appveyor should be building wheels.
