### ISSUE TITLE
Automatic PyPI uploads are failing: `zope.wheelbuilder` needs a verified primary email

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/persistent#73]
See [this build for 4.3.0](https://travis-ci.org/zopefoundation/persistent/jobs/409969188#L315):
```
HTTPError: 400 Client Error: User 'zope.wheelbuilder' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/
```

Warehouse issue: https://github.com/pypa/warehouse/issues/3632

**Comment by tseaver** [comment]
I'm not sure who has the keys to the `zope.wheelbuilder` account. Could be one of:

- @mgedmin 
- @icemac 
- @agroszer

**Comment by mgedmin** [comment]
Oh, whoops!  Should've thought of that!  I'll take care of it ASAP.

Currently my email is the only one attached to zope.wheelbuilder, but PyPI allows attaching multiple emails.  @tseaver would you like me to add yours?

**Comment by mgedmin** [comment]
The email is verified, and I've restarted all the failed persistent MacOS & manylinux build jobs on Travis for 4.3.0.

**Comment by jamadden** [comment]
Thank you!

Could you also please rebuild the commit [on AppVeyor](https://ci.appveyor.com/project/mgedmin/persistent)?

**Comment by mgedmin** [comment]
Rebuild queued: https://ci.appveyor.com/project/mgedmin/persistent/build/1.0.121
