### ISSUE TITLE
Can we require CFFI for PURE_PYTHON usage on CPython?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/persistent#77]
CFFI distributes binary wheels, so it's a lightweight dependency.

This would simplify our code by letting us remove one of the two implementations of picklecache.Ring, and it would simplify our test matrix and help us reach 100% coverage.

**Comment by jamadden** [comment]
Also, with #45, I don’t want to have to implement it three times.

**Comment by jimfulton** [comment]
+1.  If it blows up in some unexpected way we can revert. :)

**Comment by icemac** [comment]
+1 from me.
