### ISSUE TITLE
Python 3.7 binary wheels on PyPI

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/persistent#85]
Currently the last `persistent` release on PyPI lacks Windows binary wheels for Python 3.7.

This can be fixed one of two ways:
- we make a new release and our appveyor.yml will build and upload all the wheels
- OR we create a temporary `appveyor` branch based on the last release tag, edit appveyor.yml to add python: 37 and 37-64, remove all other pythons from the build matrix, and make the twine upload step unconditional, push it, wait for appveyor, delete the branch

**Comment by tseaver** [comment]
Python 3.7 support was added after `4.3.0`, so we aren't really behind.  I'd say make a `4.4` release (bumping because of the new Python version).

**Comment by tseaver** [comment]
We should likely get #83 and #84 merged first.

**Comment by mgedmin** [comment]
AFAIU no actual code changes were required for Python 3.7 support, just the usual build system tweaks?

I, uh, might've jumped the gun on option 2.  Um.  The wheels are on PyPI.
