### ISSUE TITLE
Type name varies in the repr() depending on the presence of the C extension

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/persistent#92]
This manifests in breakage of [BTrees tests](https://travis-ci.org/zopefoundation/BTrees/jobs/415400906) when the C extensions are used (they pass when the pure-Python extensions are available). 

This is a somewhat common problem. There's a [python-dev thread](https://mail.python.org/pipermail/python-dev/2018-September/155150.html) and [bpo-issue](https://bugs.python.org/issue34595) about this. In particular, in the issue, and one of the [PRs that fixes it](https://github.com/python/cpython/pull/9122/) it's pointed out that getting the correct qualified name in a C type can be complex depending on things like `Py_TPFLAGS_HEAPTYPE` (and that's just on Python 3, I don't know if there's an equivalent of `ht_qualname` on Python 2).

Is this a bug here that we should fix, or should downstream consumers be prepared to deal with the difference? In one of my own downstream projects I dealt with the difference. But BTrees already deals with the difference in its own code to produce equivalent reprs in Python as we *used* to get from C.  (See https://github.com/zopefoundation/BTrees/issues/94)

**Comment by jamadden** [comment]
> Is there any reason not to fix the instance reprs to avoid this issue?

I'm not quite sure what you mean. If you're asking, "can we make a change to cPersistence.Persistent to report the qualified name", my only answer is "it can be complicated" as discussed in the python-dev thread. Right now it's doing the simplest possible thing (largely because I don't consider myself a C API expert so I kept it simple). If you're asking "can we make a change to persistentce.Persistent to use the simple name", sure, we could, but we lose the module name, which is often useful. (That's a change I could implement.)

I'm not sure how big an issue this really is. BTrees was simple to fix. Still, it's an observable difference.

**Comment by jimfulton** [comment]
IDK :) Perhaps we expose the logical module name (e.g. BTrees.IOBTree.BTree) rather than the actual one.

IDK how big an issue it is either.
